/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Reg API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

export interface Ingredient {
  id?: number;
  name?: string;
  amount?: string;
  date?: string;
}

export interface IngredientInput {
  name: string;
  amount: string;
  date: string;
}

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;




/**
 * @summary 모든 재료 조회
 */
export type getIngredientsResponse200 = {
  data: Ingredient[]
  status: 200
}

export type getIngredientsResponseSuccess = (getIngredientsResponse200) & {
  headers: Headers;
};
;

export type getIngredientsResponse = (getIngredientsResponseSuccess)

export const getGetIngredientsUrl = () => {




  return `/ingredients`
}

export const getIngredients = async ( options?: RequestInit): Promise<getIngredientsResponse> => {

  const res = await fetch(getGetIngredientsUrl(),
  {
    ...options,
    method: 'GET'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getIngredientsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getIngredientsResponse
}





export const getGetIngredientsQueryKey = () => {
    return [
    `/ingredients`
    ] as const;
    }


export const getGetIngredientsQueryOptions = <TData = Awaited<ReturnType<typeof getIngredients>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIngredients>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetIngredientsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getIngredients>>> = ({ signal }) => getIngredients({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getIngredients>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetIngredientsQueryResult = NonNullable<Awaited<ReturnType<typeof getIngredients>>>
export type GetIngredientsQueryError = unknown


export function useGetIngredients<TData = Awaited<ReturnType<typeof getIngredients>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIngredients>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getIngredients>>,
          TError,
          Awaited<ReturnType<typeof getIngredients>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetIngredients<TData = Awaited<ReturnType<typeof getIngredients>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIngredients>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getIngredients>>,
          TError,
          Awaited<ReturnType<typeof getIngredients>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetIngredients<TData = Awaited<ReturnType<typeof getIngredients>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIngredients>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 모든 재료 조회
 */

export function useGetIngredients<TData = Awaited<ReturnType<typeof getIngredients>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIngredients>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetIngredientsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





/**
 * @summary 재료 등록
 */
export type postIngredientsResponse201 = {
  data: Ingredient
  status: 201
}

export type postIngredientsResponseSuccess = (postIngredientsResponse201) & {
  headers: Headers;
};
;

export type postIngredientsResponse = (postIngredientsResponseSuccess)

export const getPostIngredientsUrl = () => {




  return `/ingredients`
}

export const postIngredients = async (ingredientInput: IngredientInput, options?: RequestInit): Promise<postIngredientsResponse> => {

  const res = await fetch(getPostIngredientsUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      ingredientInput,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postIngredientsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postIngredientsResponse
}




export const getPostIngredientsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postIngredients>>, TError,{data: IngredientInput}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postIngredients>>, TError,{data: IngredientInput}, TContext> => {

const mutationKey = ['postIngredients'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postIngredients>>, {data: IngredientInput}> = (props) => {
          const {data} = props ?? {};

          return  postIngredients(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostIngredientsMutationResult = NonNullable<Awaited<ReturnType<typeof postIngredients>>>
    export type PostIngredientsMutationBody = IngredientInput
    export type PostIngredientsMutationError = unknown

    /**
 * @summary 재료 등록
 */
export const usePostIngredients = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postIngredients>>, TError,{data: IngredientInput}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postIngredients>>,
        TError,
        {data: IngredientInput},
        TContext
      > => {
      return useMutation(getPostIngredientsMutationOptions(options), queryClient);
    }

/**
 * @summary 재료 수정
 */
export type putIngredientsIdResponse200 = {
  data: Ingredient
  status: 200
}

export type putIngredientsIdResponseSuccess = (putIngredientsIdResponse200) & {
  headers: Headers;
};
;

export type putIngredientsIdResponse = (putIngredientsIdResponseSuccess)

export const getPutIngredientsIdUrl = (id: number,) => {




  return `/ingredients/${id}`
}

export const putIngredientsId = async (id: number,
    ingredientInput: IngredientInput, options?: RequestInit): Promise<putIngredientsIdResponse> => {

  const res = await fetch(getPutIngredientsIdUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      ingredientInput,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: putIngredientsIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as putIngredientsIdResponse
}




export const getPutIngredientsIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putIngredientsId>>, TError,{id: number;data: IngredientInput}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof putIngredientsId>>, TError,{id: number;data: IngredientInput}, TContext> => {

const mutationKey = ['putIngredientsId'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putIngredientsId>>, {id: number;data: IngredientInput}> = (props) => {
          const {id,data} = props ?? {};

          return  putIngredientsId(id,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutIngredientsIdMutationResult = NonNullable<Awaited<ReturnType<typeof putIngredientsId>>>
    export type PutIngredientsIdMutationBody = IngredientInput
    export type PutIngredientsIdMutationError = unknown

    /**
 * @summary 재료 수정
 */
export const usePutIngredientsId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putIngredientsId>>, TError,{id: number;data: IngredientInput}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putIngredientsId>>,
        TError,
        {id: number;data: IngredientInput},
        TContext
      > => {
      return useMutation(getPutIngredientsIdMutationOptions(options), queryClient);
    }

/**
 * @summary 재료 삭제
 */
export type deleteIngredientsIdResponse204 = {
  data: void
  status: 204
}

export type deleteIngredientsIdResponseSuccess = (deleteIngredientsIdResponse204) & {
  headers: Headers;
};
;

export type deleteIngredientsIdResponse = (deleteIngredientsIdResponseSuccess)

export const getDeleteIngredientsIdUrl = (id: number,) => {




  return `/ingredients/${id}`
}

export const deleteIngredientsId = async (id: number, options?: RequestInit): Promise<deleteIngredientsIdResponse> => {

  const res = await fetch(getDeleteIngredientsIdUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteIngredientsIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteIngredientsIdResponse
}




export const getDeleteIngredientsIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteIngredientsId>>, TError,{id: number}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deleteIngredientsId>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteIngredientsId'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteIngredientsId>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteIngredientsId(id,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteIngredientsIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteIngredientsId>>>

    export type DeleteIngredientsIdMutationError = unknown

    /**
 * @summary 재료 삭제
 */
export const useDeleteIngredientsId = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteIngredientsId>>, TError,{id: number}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteIngredientsId>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeleteIngredientsIdMutationOptions(options), queryClient);
    }
