/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * 제로냉 레시피 API
 * 냉장고 속 재료로 만드는 꿀조합 레시피 조회 API
 * OpenAPI spec version: 1.0.0
 */
import type { RecipeDifficulty } from './recipeDifficulty';

export interface Recipe {
  /** 분 단위 */
  cookingTime?: number;
  description?: string;
  difficulty?: RecipeDifficulty;
  id: number;
  ingredients: string[];
  title: string;
}
