/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * 제로냉 레시피 API
 * 냉장고 속 재료로 만드는 꿀조합 레시피 조회 API
 * OpenAPI spec version: 1.0.0
 */

export type RecipeDifficulty = typeof RecipeDifficulty[keyof typeof RecipeDifficulty];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RecipeDifficulty = {
  EASY: 'EASY',
  NORMAL: 'NORMAL',
  HARD: 'HARD',
} as const;
