/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * 제로냉 레시피 API
 * 냉장고 속 재료로 만드는 꿀조합 레시피 조회 API
 * OpenAPI spec version: 1.0.0
 */
import type { Recipe } from './recipe';

export type Recipes = Recipe[];
